### ISSUE TITLE
Send out wrapping-up email to speakers

### ISSUE THREAD

**Issue by sphuber** [MADICES/MADICES-2022#37]
Include 

- Thanking for presenting and participating
- Link to survey https://forms.gle/CAKiGcK8JxpNWPD26
- Request permission to share recordings on youtube
- Request copy of their slides (drive folder: https://drive.google.com/drive/u/1/folders/1seezApNep0wSFD6aqD-ZqcF3fjFqBj4I)
- Ask if they want to participate in writing the perspective

**Comment by ml-evs** [comment]
donezo :100:
